-- *************************************************
-- ***   Create View MANRANK
-- *************************************************
   DROP VIEW IF EXISTS MANRANK;
CREATE OR REPLACE VIEW MANRANK
	(SCLMANNO, MANNM, TANNO, LESSONKBN) 
AS 
SELECT 
 A.SCLMANNO,A.MANNM, T1.TANNO, T2.LESSONKBN
FROM
 MANMST A,
(
SELECT 
 RANK() OVER (PARTITION BY SCLMANNO ORDER BY COUNT(TANNO) DESC, TANNO) AS CNTRANK,
 COUNT(TANNO),
 SCLMANNO,
 TANNO
FROM 
 ATDTRN
WHERE
 DATKB = '1'
GROUP BY 
 SCLMANNO,
 TANNO
) T1,
(
SELECT 
 RANK() OVER (PARTITION BY SCLMANNO ORDER BY COUNT(LESSONKBN) DESC, LESSONKBN) AS CNTRANK,
 COUNT(LESSONKBN),
 SCLMANNO,
 LESSONKBN
FROM 
 ATDTRN
WHERE
 DATKB = '1'
GROUP BY 
 SCLMANNO,
 LESSONKBN
) T2
WHERE 
 A.SCLMANNO = T1.SCLMANNO
 AND A.SCLMANNO = T2.SCLMANNO
 AND T1.CNTRANK = 1
 AND T2.CNTRANK = 1
;